### ISSUE TITLE
Any plans to support "raw", or free form, message processing?

### ISSUE THREAD

**Issue by chids** [blacklocus/queue-slayer#10]
Howdy :tada:

I like what you've done here :+1: and would personally like to use this library to process "raw" messages in various JSON formats. Any thoughts on making the code support arbitrary message formats? I'm primarily referring to not requiring messages to conform to the format imposed by `QSTaskModel`.

**Comment by dirkraft** [comment]
Hi, this is late so probably doesn't matter, but as is probably obvious, we haven't had a chance to really develop this lib. I'll be removing QSAssembly/worker-related components pretty soon to slim down to the original critical parts first open sourced (the QueueReader pattern). This repo is [apache 2](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) license so you are free to do whatever fun stuff you want in accordance with that license.
